[package]
name = "mongo-file-center"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/mongo-file-center"
homepage = "https://magiclen.org/mongo-file-center"
keywords = ["mongodb", "storage", "file", "rocket"]
categories = ["filesystem", "database", "web-programming"]
description= "A file center based on MongoDB."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/mongo-file-center", branch = "master" }
appveyor = { repository = "magiclen/mongo-file-center", branch = "master", service = "github" }

[dependencies]
mongodb = { git = "https://github.com/magiclen/mongo-rust-driver-prototype", branch = "master" }
#mongodb = "0.3.10"
bson = "0.13"
short-crypt = "1.0.4"
lazy_static = "1.1.0"
chrono = "0.4.6"
sha3 = "0.8.0"
mime_guess = "1.8.6"
regex = "1.0.5"